### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by ryannix123** [jupyter-on-openshift/jupyter-notebooks#1]
Hi @GrahamDumpleton,

When I deploy in my single-node cluster, I get the error: 

`

12:54:00 PM | my-notebook-2-zmcps | Pod | Warning | Failed Scheduling | 0/1 nodes are available: 1 Insufficient pods.20 times in the last 4 minutes
-- | -- | -- | -- | -- | --
12:49:39 PM | my-notebook-2 | Replication Controller | Normal | Successful Create | Created pod: my-notebook-2-zmcps
12:49:38 PM | my-notebook-2-deploy | Pod | Normal | Started | Started container
12:49:38 PM | my-notebook-2-deploy | Pod | Normal | Created | Created container
12:49:38 PM | my-notebook-2-deploy | Pod | Normal | Pulled | Container image "openshift/origin-deployer:v3.9.0" already present on machine
12:49:33 PM | my-notebook-2-deploy | Pod | Normal | Successful Mount Volume | MountVolume.SetUp succeeded for volume "deployer-token-w4rxh"
12:49:33 PM | my-notebook-2-deploy | Pod | Normal | Scheduled | Successfully assigned my-notebook-2-deploy to cloudapps.northwestern.edu
12:49:32 PM | my-notebook | Deployment Config | Normal | Deployment Created | Created new replication controller "my-notebook-2" for version 2

`

Any ideas?

- Ryan

**Comment by GrahamDumpleton** [comment]
There is a limit on the number of pods that can be scheduled to nodes in a cluster. This is dictated by amount of resources (based on CPU cores by default I believe) nodes have. The error indicates that the number of pods attempting to be scheduled to the node has exceeded that limit. This limit is a system configuration value, so only your cluster admins can do anything about it. In short, it generally indicates the system believes it is overloaded.

See:

* https://docs.openshift.com/container-platform/3.9/scaling_performance/cluster_limits.html#scaling-performance-current-cluster-limits

**Comment by ryannix123** [comment]
Thanks! I'm also running OpenWhisk on @gshipley 's single node OpenShift Origin instance for demo purposes, so I assume that is the issue.

P.S. Thank you also for signing a copy of your book at Summit!  @GrahamDumpleton @gshipley

**Comment by GrahamDumpleton** [comment]
Closing this as assuming nothing to be done.
