### ISSUE TITLE
Fix JupyterLab Build by updating jupyterlab/hub-extension from 0.8.2 to 0.12.0

### ISSUE THREAD

**Issue by juliusvonkohout** [jupyter-on-openshift/jupyter-notebooks#2]
Please merge https://github.com/juliusvonkohout/jupyter-notebooks/commit/4a2f2e29168fce6feb90179b0545475957c1205a

```
@jupyterlab/hub-extension@0.8.2" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=0.16.0 <0.17.0 @jupyterlab/application
>=0.19.1 <0.20.0        >=0.16.0 <0.17.0 @jupyterlab/apputils
>=2.2.1 <3.0.0 >=1.1.0 <2.0.0 @jupyterlab/coreutils
```

**Comment by GrahamDumpleton** [comment]
Should hopefully be addressed in latest 2.0.0 tag.

Note that if you weren't using a tagged version previously and using ``oc create`` on files direct out of master, that will likely fail now as supplied build configs and templates have been separated into separate files in sub directories.
