### ISSUE TITLE
No Persistent Storage for Individual Pods

### ISSUE THREAD

**Issue by afeiszli** [jupyter-on-openshift/jupyter-notebooks#4]
Hi @GrahamDumpleton,

I am deploying JupyterHub on OpenShift from your image with the minimal-notebook, using OAuth + KubeSpawn to spin up individual user servers. I would like to have persistent storage for those individual pods, so that when they go down they do not lose their data. Is this a possibility?

Thanks,
Alex

**Comment by GrahamDumpleton** [comment]
When you say 'Auth + KubeSpawn' do you mean JupyterHub? Or are you using some other solution to start up notebook instances? If using JupyterHub, are you using a JupyterHub setup you created yourself, or one of those under the 'jupyter-on-openshift' organisation on GitHub.

**Comment by blaisep** [comment]
Hi @grahamdumpleton I guess you can close this issue since @afeiszli has not replied...

**Comment by juliusvonkohout** [comment]
We have this in production using jupyter-on-openshift jupyterhub images on openshift 3.10. So it works. Please close the issue.

**Comment by afeiszli** [comment]
Hi yes, just to confirm this is working fine.
